### ISSUE TITLE
Dynamic batching for onnx

### ISSUE THREAD

**Issue by aganesh9** [Kazuhito00/MVANet-ONNX-Sample#1]
Hi Kazuhito00,

Thanks for providing this code, very useful!

Is it possible to provide an ONNX model that supports dynamic batching for the input and output ? I tried to run your script with support for batching but having some environmental issues. 

Thanks!

**Comment by Kazuhito00** [comment]
Sorry, but the conversion to make batch processing dynamic was not successful when I tried it.
